[package]
name = "aulas_rust"
version = "0.1.0"
authors = ["foxx3r <coluna123@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
