[package]
name = "deref"
version = "0.1.0"
authors = ["u0_a124 <coluna123@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
lto = true
opt-level = 0
panic = 'abort'

[dependencies]
